### ISSUE TITLE
GUI with browsing server

### ISSUE THREAD

**Issue by alexmc1510** [coussej/node-opcua-logger#25]
Hello,
It is thought to develop a GUI where you can browse for tags over the OPC server? When you are reading almost 1000 tags and you need to update the client because the server has increased no of tags it's a bit painful. I have developed a macro which import a CSV from the server and export it in config.toml but I thing it's only a workaround.

Than you for the support.

**Comment by coussej** [comment]
Hi Alex, unfortunately that is not something we foresee in this community version
