### ISSUE TITLE
Modbus RTU / TCP

### ISSUE THREAD

**Issue by amarpremk** [coussej/node-opcua-logger#27]
looking forward to Modbus RTU / TCP logger for InfluxDB.

**Comment by coussej** [comment]
Hi amar, we don't foresee a modbus logger at this time.

Have you checked out [Kepware for Modbus](https://www.kepware.com/en-us/products/kepserverex/suites/modbus-suite/)? That can translate modbus to OPCUA, and then you can just use this logger.
