### ISSUE TITLE
Metrics Configuration

### ISSUE THREAD

**Issue by DavidWicks** [coussej/node-opcua-logger#38]
Is there any examples/documentation of Metrics configurations ?
I am having problems understanding this, in particular the nodeId.
Would you be able to provde the correct configutation details for this example simulation in KepEX
Do I need to create an Alias first ?

![Random Number](https://user-images.githubusercontent.com/26701506/74168950-7a91ba00-4c65-11ea-8eb7-6f7fb6b2a853.PNG)

![Tag 1](https://user-images.githubusercontent.com/26701506/74169457-4ff43100-4c66-11ea-97fb-a84654fe6dee.PNG)

**Comment by coussej** [comment]
Hi David, 

Kepware exposes everything in namespace 2. After that, the nodeId is just the same path as you can see with the OPC quick client (accessible from the admin). For your examples, the nodeId's would be:

```
ns=2;s=Simulation Examples.Functions.Random2 (not sure about the space though)
ns=2;s=Channel1.Device1.Tag1
```

Does that make sense?

**Comment by DavidWicks** [comment]
Thank you for the reply :)  

Yes it does make sense.  I am finding that there does not seem to be any solid reference data for the format of NodeID. (some conflicting info as well)

I also confirmed with Kepware that the NodeID namespace for the KepserverEx is fixed at 2.

The space between **_Simulation_** and **_Examples_** is valid.

I am now succesfully receiving simulation data into InfluxDB.
