### ISSUE TITLE
Synchronize node-opcua with Databases

### ISSUE THREAD

**Issue by UmerIftikhar** [coussej/node-opcua-logger#4]
How can I make it work both ways. For example, if some thing(a particular row in a table is modified, added or deleted) is changed in my DB, how can I let my opcua server know about it?

**Comment by coussej** [comment]
From what you describe, I think you are looking for some event system to collect events from a PLC and write them in an SQL table, and at the same time read events from another SQL table and write them to the PLC. That is not the purpose of this library: it is a read-only data collector for pushing OPCUA data to InfluxDB. There is no intention to add write functionality.

For your goal, I suggest you write a new application with [NodeOPCUA](http://node-opcua.github.io/), the same OPC library used here.
