### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by anantmk** [coussej/node-opcua-logger#41]
Hi Jeroen,

I am trying to test your opcua-logger. After **npm run start** I get an error because of no certificate. 

I have a machine with no internet access. Could you help me with this?

Thanks, Anant

Please see the logs:

![image](https://user-images.githubusercontent.com/19150567/75561735-ca36fa80-5a47-11ea-81eb-f6aab4f52068.png)

![image](https://user-images.githubusercontent.com/19150567/75561920-0f5b2c80-5a48-11ea-986f-c169e82ec29d.png)

**Comment by coussej** [comment]
Hello,

did you run npm install on that same machine, or did you run it on a
different machine and then copied the folder?

In you case, the best thing to do is download a prebuilt binary. That
contains everything you need in a singe binary, and should run without
issues.

**Comment by anantmk** [comment]
Thank you. The binary is working well!

Br, Anant
