### ISSUE TITLE
cannot start the Win-64 service

### ISSUE THREAD

**Issue by jasonye87** [coussej/node-opcua-logger#47]
Hello Sir,

I tried to run the Win-64 .exe service and it throws out an error pointing to 
node-opcua-logger\node-modules\toml\lib\parser.js:3833 as shown in the capture.
![image](https://user-images.githubusercontent.com/56623479/82975639-a74cc000-a00f-11ea-8801-6cfefc84638a.png)

Could you help check the error and share the solution?

Thanks,
Jason

**Comment by coussej** [comment]
Passing the config file with a flag won't work, if you want to use a custom location you should set it in the Environment (see also https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt)

However, `config.toml` is the default location for the config file, and from the syntax error it looks like it's not formatted correctly. The error specifies it found a `{`, did you perhaps use JSON instead of TOML? 

Can you share the contents of the file here?

**Comment by jasonye87** [comment]
Thanks for the reply, Jeroen.
After changing the config.toml file along with the sample file, now the application works well.

Just curious about how to set and use config.json file instead?

Regards,
Jason
________________________________
发件人: Jeroen Coussement <notifications@github.com>
发送时间: 2020年5月27日 16:49
收件人: coussej/node-opcua-logger <node-opcua-logger@noreply.github.com>
抄送: jasonye87 <shenxi_ye@outlook.com>; Author <author@noreply.github.com>
主题: Re: [coussej/node-opcua-logger] cannot start the Win-64 service (#47)


Passing the config file with a flag won't work, if you want to use a custom location you should set it in the Environment (see also https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt)

However, config.toml is the default location for the config file, and from the syntax error it looks like it's not formatted correctly. The error specifies it found a {, did you perhaps use JSON instead of TOML?

Can you share the contents of the file here?

―

**Comment by coussej** [comment]
Hello, 

the application determines the format based on the extension of the config file. You would set the necessary environment variable by running the following command:
```
set CONFIG_FILE=c:\path\to\config.json
```
and then in the same command line window you run the binary of the logger! 

Usually, after testing config etc, you'd run the logger through a windows service. I usually suggest using [nssm](https://nssm.cc/) to do so. During the installation, you can also specify the environment variables for the service.

**Comment by jasonye87** [comment]
Got it, thanks for the help!
________________________________
发件人: Jeroen Coussement <notifications@github.com>
发送时间: 2020年5月27日 22:02
收件人: coussej/node-opcua-logger <node-opcua-logger@noreply.github.com>
抄送: jasonye87 <shenxi_ye@outlook.com>; Author <author@noreply.github.com>
主题: Re: [coussej/node-opcua-logger] cannot start the Win-64 service (#47)


Hello,

the application determines the format based on the extension of the config file. You would set the necessary environment variable by running the following command:

set CONFIG_FILE=c:\path\to\config.json


and then in the same command line window you run the binary of the logger!

Usually, after testing config etc, you'd run the logger through a windows service. I usually suggest using nssm<https://nssm.cc/> to do so. During the installation, you can also specify the environment variables for the service.

―

**Comment by coussej** [comment]
You're welcome!
