### ISSUE TITLE
[Question] Adding OPCUA Tag while running

### ISSUE THREAD

**Issue by henjoe** [coussej/node-opcua-logger#70]
Hi Coussej, 

First of all, I would like to commend you for this great project! Indeed your ideas of combining OT-IT as the future trend was so amazing.  

In anyways, I would like to ask if it is possible that this tool, while it is running can we add a Tags on it? like simply adding a [[measurement]] on a config.toml. Does it needs to be restarted before the added [[measurements]] take effects? I am just thinking that if we restarted it, there will be a lost of data.

Again. Thank you on your greate work!

Regards,
Henjoe

**Comment by coussej** [comment]
Yes, in this open source implementation the application has to be restarted to reload the config file. The commercial version we've developed with Factry has an advanced management UI where tags can be added and modified on the fly, without interrupting the others.

**Comment by henjoe** [comment]
Hi @coussej ,

Do you have any contacts with your developed UI for commercial side?
Let me try to contact you.

**Comment by coussej** [comment]
You can use one of the contact methods on https://www.factry.io/ and refer to this conversation, it will end up with me then ;-) thanks!
