### ISSUE TITLE
[Question] Clarification on the side of BatchSize, buffer.js

### ISSUE THREAD

**Issue by henjoe** [coussej/node-opcua-logger#71]
Hi Coussej,

I am wondering what is the meaning of this configuration on the side of Buffer.js 
![image](https://user-images.githubusercontent.com/49782655/123200044-973d3380-d4e2-11eb-988c-26c2fd0aec35.png)

Does it mean only 1000 Tags are going to buff? 
I received warnings that may memBuffer already exceed a maximum of 1000. 
Is is something to do with the batchSize right? 

Thank you,

**Comment by coussej** [comment]
Hi @henjoe,

That simply means the maximum batch size that will be written to influx. Let's say you have 2000 metrics per second, they will be written to influx in 2 batches of 1000 points. You can increase that if you have more.

It is not related to the amount of tags that are going to be buffered.

Regards,
Jeroen

**Comment by henjoe** [comment]
Hi @coussej 
Thanks for this! :) 

Higly appreciated your work here.
